version: '3.8'

services:

  db:
    image: postgres
    container_name: lyv_database
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      SECRET_KEY: my_secret_key
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network

  web:
    build: .
    environment:
      - SECRET_KEY=my_secret_key
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - custom_network

volumes:
  postgres_data:

networks:
  custom_network:
    driver: bridge
